# Use an official Node.js runtime as a parent image
FROM node:23.11-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application code into the container
COPY . .

# Build the app - TypeScript transpiled
RUN npm run build

# Expose the port your app will run on
EXPOSE ${BACKEND_PORT}

# Run the application
CMD ["npm", "start"]
